packages:
  - "packages/blob"
  - "packages/dduf"
  - "packages/hub"
  - "packages/inference"
  - "packages/doc-internal"
  - "packages/agents"
  - "packages/languages"
  - "packages/tasks"
  - "packages/tasks-gen"
  - "packages/gguf"
  - "packages/jinja"
  - "packages/space-header"
  - "packages/ollama-utils"
  - "packages/mcp-client"
  - "packages/tiny-agents"
  - "packages/gearhash-wasm"
  - "packages/blake3-wasm"
  - "packages/xetchunk-wasm"
  - "packages/splitmix64-wasm"
