name: Tasks - Update specs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Every day at 3am

concurrency:
  group: update-specs
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/tasks-gen

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          run_install: true

      # Generate specs
      # - run: pnpm run inference-tgi-import
      - run: pnpm run inference-tei-import
      - run: pnpm run inference-codegen

      # Check changes
      - run: git status

      # Create or update Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ secrets.TOKEN_INFERENCE_SYNC_BOT }}
          commit-message: Update tasks specs (automated commit)
          branch: update-tasks-specs-automated-pr
          delete-branch: true
          title: "[Bot] Update tasks specs"
          body: |
            This PR updates the @huggingface/tasks specs. It has been generated by running:
            ```sh
            pnpm run inference-tei-import
            pnpm run inference-codegen
            ```

            This PR was automatically created by the [Tasks - Update specs workflow](https://github.com/huggingface/huggingface.js/blob/main/.github/update-specs.yml).

            Make sure the changes are correct before merging.
          labels: |
            tasks
            specs
          reviewers: |
            Wauplin
            hanouticelina
