name: Tasks - Update specs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Every day at 3am

concurrency:
  group: update-specs
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/tasks-gen

permissions: {}

jobs:
  pull_request:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v2
        with:
          run_install: true

      # Generate specs
      # - run: pnpm run inference-tgi-import
      - run: pnpm run inference-tei-import
      - run: pnpm run inference-codegen

      # Check changes
      - run: git status

      # Create or update Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.TOKEN_INFERENCE_SYNC_BOT }}
          commit-message: Update tasks specs (automated commit)
          branch: update-tasks-specs-automated-pr
          delete-branch: true
          title: "[Bot] Update tasks specs"
          body: |
            This PR updates the @huggingface/tasks specs. It has been generated by running:
            ```sh
            pnpm run inference-tei-import
            pnpm run inference-codegen
            ```

            This PR was automatically created by the [Tasks - Update specs workflow](https://github.com/huggingface/huggingface.js/blob/main/.github/update-specs.yml).

            Make sure the changes are correct before merging.
          labels: |
            tasks
            specs
          reviewers: |
            Wauplin
            hanouticelina
